Fix permission and missed file issue.

diff --git a/scripts/clonedetect/paramsetting_groupfile b/scripts/clonedetect/paramsetting_groupfile
--- a/scripts/clonedetect/paramsetting_groupfile
+++ b/scripts/clonedetect/paramsetting_groupfile
@@ -33,16 +33,41 @@
 # 
 #
 
-if [[ $# -ne 3 ]]; then
-	echo "Usage: $0 <a param file> <dimension> <dist>"
-	exit 65
+# Usage: $1=min_token, $2=stride, $3=similarity, $4=groupfortuning, $5=vecgroup_filename
+
+# make sure ${GROUPING_S} and ${VECTOR_DIR} are set correctly.
+
+if [[ $# -ne 5 ]]; then
+   echo "Error: wrong parameters for paramsetting_groupfile: $@"
+   echo "Usage: $0 min_token stride similarity vecgroup_filename groupfortuning vecgroup_filename"
+   exit 65
 fi
 
-head -n 2 "$1"
-echo $3
-head -n 8 "$1" | tail -n 5
-echo $3 | awk '{printf("%.7g\n", $1*$1)}'
-head -n 20 "$1" | tail -n 11
-echo $2
-tail -n 2 "$1"
+# TODO: may check whether parameters have been set or not...
+
+t=$1
+s=$2
+sim=$3
+groupfortuning=$4
+vdb=$5
+
+# convert SIMILARITY to DISTANCE:
+i=`echo "$sim ${GROUPING_S}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
+
+grptuningid=`echo ${groupfortuning} | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
+grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
+grpal=0
+grpdist=0
+if [[ ${grptuningid} -eq $grpfileid ]]; then
+   exit 0
+elif [[ $grpfileid -eq 1 ]]; then
+   grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
+   grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
+else
+   grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
+   grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
+fi
+lineno=`wc -l "$vdb" | awk '{print $1}'`
+lineno=$(($lineno / 2))
+"`dirname $0`/generateparam" "${groupfortuning}.param" $lineno $grpdist > "${vdb}.param"
 
diff --git a/scripts/clonedetect/vdbclustergroup b/scripts/clonedetect/vdbclustergroup
--- a/scripts/clonedetect/vdbclustergroup
+++ b/scripts/clonedetect/vdbclustergroup
@@ -33,16 +33,42 @@
 # 
 #
 
-if [[ $# -ne 3 ]]; then
-	echo "Usage: $0 <a param file> <dimension> <dist>"
-	exit 65
+#vector clustering for each group: $1=min_token, $2=stride, $3=similarity, $4=vecgroup_filename
+if (($# != 4));
+then
+   echo "Error: wrong parameters for vdbclustergroup: $@"
+   echo "Usage: $0 min_token stride similarity vecgroup_filename"
+   exit 65
 fi
 
-head -n 2 "$1"
-echo $3
-head -n 8 "$1" | tail -n 5
-echo $3 | awk '{printf("%.7g\n", $1*$1)}'
-head -n 20 "$1" | tail -n 11
-echo $2
-tail -n 2 "$1"
+t=$1
+s=$2
+sim=$3
+vdb=$4
+
+# convert SIMILARITY to DISTANCE used by LSH:
+#       (1) always round up; (2) different for different code sizes; (3) require 'awk' for sqrt
+i=`echo "$sim ${GROUPING_S}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
+
+grpfileid=`echo "$vdb" | sed "s/.*vdb_${t}_${s}_g\([0-9]*\)_${i}_${GROUPING_S}.*/\1/"`
+grpal=0
+grpdist=0
+# TODO: what are better distance parameters for the groups?
+if [[ $grpfileid -le 0 ]]; then
+   echo "Warning: invalid group id: $grpfileid in group $vdb...Skip." | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
+   exit 1
+elif [[ $grpfileid -eq 1 ]]; then
+   grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $3}'`
+   grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*$2) )}'`
+else
+   grpal=`head -n $(expr $grpfileid + 1) $(dirname "$vdb")/ranges_${i}_${GROUPING_S} | tail -n 1 | awk '{print $2}'`
+   grpdist=`echo "$sim ${grpal}" | awk '{printf( "%.7g\n", sqrt((1-$1)*2*$2) )}'`
+fi
+cluster "$vdb" $grpdist 1>>"$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}" 2>&1
+errcode=$?
+if [[ $errcode -ne 0 ]]; then
+   echo "Clustering: Possible errors for vector group: $vdb $grpdist. Check log: $TIME_DIR/cluster_$(basename "${vdb}")" | tee -a "$TIME_DIR/cluster_vdb_${t}_${s}_allg_${i}_${GROUPING_S}"
+fi
+
+exit $errcode
 
diff --git a/scripts/clonedetect/vdbgenfile b/scripts/clonedetect/vdbgenfile
--- a/scripts/clonedetect/vdbgenfile
+++ b/scripts/clonedetect/vdbgenfile
@@ -33,16 +33,20 @@
 # 
 #
 
-if [[ $# -ne 3 ]]; then
-	echo "Usage: $0 <a param file> <dimension> <dist>"
-	exit 65
+#vdbgenfile $1 $2 $3: $1=min_token; $2=stride; $3=file
+
+if (($# != 3));
+then
+   echo "Error: wrong parameters for vdbgenfile: $@"
+   echo "Usage: $0 min_token stride filename"
+   exit 65
 fi
 
-head -n 2 "$1"
-echo $3
-head -n 8 "$1" | tail -n 5
-echo $3 | awk '{printf("%.7g\n", $1*$1)}'
-head -n 20 "$1" | tail -n 11
-echo $2
-tail -n 2 "$1"
+echo "Parsing $3" >> "$TIME_DIR/vgen_$1_$2" &&
+if [[ ! -s "$3.vec" || "$TOOVERWRITE" = "true" ]];
+then
+   "$VGEN_EXEC" -i "$3" -m $1 -t $2 1>>"$TIME_DIR/vgen_$1_$2" 2>&1
+else
+   echo "Warning: $3.vec exists, and no overwrite."
+fi
 
